version: '3.8'

services:
  backend:
    image: robinwinters/smartzer-backend:latest
    container_name: smartzer-backend
    ports:
      - '3333:3333'
    restart: always

  frontend:
    image: robinwinters/smartzer-frontend:latest
    container_name: smartzer-frontend
    ports:
      - '4200:80'
    depends_on:
      - backend
    restart: always
