name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint frontend
        run: npx nx lint frontend

      - name: Build frontend
        run: npx nx build frontend

      - name: Run frontend tests
        run: npx nx test frontend

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get version from package.json
        id: version
        run: echo "version=$(jq -r .version frontend/package.json)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            robinwinters/smartzer-frontend:latest
            robinwinters/smartzer-frontend:${{ steps.version.outputs.version }}
