name: Publish Docker Compose File

on:
  push:
    branches:
      - main

jobs:
  publish-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Copy docker-compose template
        run: cp compose-template.yml docker-compose.yml

      - name: Commit and push docker-compose.yml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docker-compose.yml
          git commit -m "Update docker-compose.yml [auto]" || echo "No changes"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}
