name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC

permissions:
  contents: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Run Renovate via Docker
        uses: docker://ghcr.io/renovatebot/renovate:latest
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
        with:
          args: 'robinucar/smartzer-tech-test'
