name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Renovate CLI
        run: npm install --no-save renovate

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx renovate
